[versions]
plexus-compiler = "2.15.0"
javax-inject = "1"

[libraries]
plexus-compiler-api = { module = "org.codehaus.plexus:plexus-compiler-api", version.ref = "plexus-compiler" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }

[plugins]