name: "Build"

"on":
  workflow_call:
    inputs:
      runner:
        description: "Runner"
        required: false
        type: string
        default: "ubuntu-latest"
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: "read"

jobs:
  build:
    name: "Maven Plugin"
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: "read"
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15
        with:
          disable-sudo: true
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: "Setup: JDK"
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: graalvm
          java-version: "25"
      - name: "Setup: Elide"
        uses: elide-dev/setup-elide@d91d5859c0722417ea1ac4c682382ac8a6622b80 # v3.0.0
      - name: "Build: Java Compiler"
        run: ./mvnw clean install -pl plexus-compilers
      - name: "Build: Kotlin Plugin"
        run: ./mvnw clean install -pl kotlin-plugin
      - name: "Test: Java Compiler"
        run: ./mvnw clean package -pl sample-java
      - name: "Test: Kotlin Plugin"
        run: ./mvnw clean package -pl sample-kotlin
      - name: "Test: Mixed source"
        run: ./mvnw clean package -pl sample-mixed
