name: "Build"

"on":
  workflow_call:
    inputs:
      runner:
        description: "Runner"
        required: false
        type: string
        default: "ubuntu-latest"
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: "read"

jobs:
  build:
    name: "Maven Plugin"
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: "read"
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          disable-sudo: true
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: "Setup: JDK"
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: graalvm
          java-version: "24"
      - name: "Setup: Elide"
        uses: elide-dev/setup-elide@990b915b2974a70e7654acb1303607b4cd1d3538 # v2.0.0
      - name: "Build: Plugin"
        run: ./gradlew elide-plexus-compilers:build elide-plexus-compilers:publishToMavenLocal
      - name: "Test: Plugin"
        working-directory: sample
        run: ./mvnw clean package
