name: "Build"

"on":
  workflow_call:
    inputs:
      runner:
        description: "Runner"
        required: false
        type: string
        default: "ubuntu-latest"
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        required: false
        type: string
        default: "ubuntu-latest"

permissions:
  contents: "read"

jobs:
  build:
    name: "Maven Plugin"
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: "read"
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: audit
      - name: "Setup: Checkout"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: "Setup: JDK"
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: graalvm
          java-version: "25"
      - name: "Setup: Elide"
        uses: elide-dev/setup-elide@d2f742321bf672300c0935839b6f5c6e562a965b # v4.1.0
        with:
          channel: nightly
      - name: "Build: Java Compiler"
        run: ./mvnw clean install -pl java-compiler
      - name: "Build: Kotlin Plugin"
        run: ./mvnw clean install -pl kotlin-plugin
      - name: "Build: Elide Plugin"
        run: ./mvnw clean install -pl elide-plugin
      - name: "Test: Java Compiler"
        run: ./mvnw clean package -pl sample-java
      - name: "Test: Kotlin Plugin"
        run: ./mvnw clean package -pl sample-kotlin
      - name: "Test: Mixed source"
        run: ./mvnw clean package -pl sample-mixed
