name: "PR"

"on":
  pull_request: { }

permissions:
  contents: "read"

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/job.build.yml
    secrets: inherit
    permissions:
      contents: "read"
    with:
      runner: "ubuntu-latest"
